name: Deploy Zipped Project to S3

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERSION: 1.0.0

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout and tag creation
jobs:
  BuildAndUploadToS3:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.S3_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Zip files
        id: zip_files
        run: |
          FILENAME=${{ secrets.DIST_ZIP_NAME }}-${{env.VERSION}}.zip
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          cd src
          zip -r ../$FILENAME *.py commands

      - name: Deploy to S3
        run: aws s3 cp ${{ steps.zip_files.outputs.filename }} s3://${{ secrets.BUCKET_NAME }}

  UpdateGitTag:
    runs-on: ubuntu-latest
    steps:
      - name: Define tag
        id: define_tag
        run: |
          TAG=refs/tags/${{ env.VERSION }}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "tag=$TAG"

      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Check if tag exists
        id: check_tag
        run: |
          if git tag -l "${{ steps.define_tag.outputs.tag }}" | grep -q "${{ steps.define_tag.outputs.tag }}"; then
            TAG_EXISTS=true
          else
            TAG_EXISTS=false
          fi
          echo "tag_exists=$TAG_EXISTS" >> $GITHUB_OUTPUT

      - name: Report if tag already exists
        run: |
          echo "Git tag exists: ${{ steps.check_tag.outputs.tag_exists  }}"

      - name: Create Git tag
        if: steps.check_tag.outputs.tag_exists != 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ steps.define_tag.outputs.tag }}',
              sha: context.sha
            })
