on:
  workflow_call:
    inputs:
      env:
        description: Environment to which code will be deployed
        required: true
        type: string
      version:
        description: Current app version
        required: true
        type: string
      filename:
        description: .zip filename (not including extension)
        required: true
        type: string
      lambda_name:
        description: Name of the Lambda to update
        required: true
        type: string
    secrets:
      S3_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      BUCKET_NAME:
        required: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout and tag creation

jobs:
  DeployFromS3ToLambda:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Ensure releases have a tag outside of dev.
      - name: Check Git tag
        if: ${{ inputs.env != 'dev' }}
        uses: actions/github-script@v6
        with:
          script: |
            const refResponse = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/${{ inputs.version }}'
            });

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.S3_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      # S3 Key should match filename. This should change in build.yml too if this must change.
      - name: Set S3 Key
        id: set_s3_key
        run: |
          FILENAME=${{ inputs.filename }}.zip
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          echo "Filename set as $FILENAME"

      - name: Check S3 bucket
        run: |
          aws s3api wait object-exists \
            --bucket ${{ secrets.BUCKET_NAME}} \
            --key ${{ steps.set_s3_key.outputs.filename }} \
            --cli-read-timeout 60 \
            --cli-connect-timeout 60

      - name: Update Lambda Code
        run: |
          echo "Pushing code to lambda ${{ inputs.lambda_name }}"
          aws lambda update-function-code \
            --function-name=${{ inputs.lambda_name }} \
            --s3-bucket=${{ secrets.BUCKET_NAME}} \
            --s3-key=${{ steps.set_s3_key.outputs.filename }} \
            --cli-read-timeout 60 \
            --cli-connect-timeout 60
