name: Deploy .zip from S3 to Lambda

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App Version'
        type: string
        required: true

jobs:
  DeployFromS3ToLambda:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check Git tag
        uses: actions/github-script@v6
        with:
          script: |
            const refResponse = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/${{ inputs.version }}'
            });
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.S3_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Check S3 bucket
        run: |
          aws s3api wait object-exists \
            --bucket ${{ secrets.BUCKET_NAME}} \
            --key ${{ secrets.DIST_ZIP_NAME }} \
            --cli-read-timeout 60 \
            --cli-connect-timeout 60
      - name: Update Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name=${{ secrets.LAMBDA_NAME }} \
            --s3-bucket=${{ secrets.BUCKET_NAME}} \
            --s3-key=${{ secrets.DIST_ZIP_NAME }} \
            --cli-read-timeout 60 \
            --cli-connect-timeout 60
