name: Dev Pipeline

on:
  push:
    branches-ignore:
      - main

env:
  ENV: 'dev'
  VERSION: 1.0.4

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout and tag creation

jobs:
  RunDevPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run pipeline
        uses: ./.github/templates/pipeline.yml
        with:
          env: ${{ env.ENV }}
          version: ${{ env.VERSION }}
