name: Dev Pipeline

on:
  push:
    branches-ignore:
      - main

env:
  ENV: 'dev' # Environment should be static for each env's .yml file.
  VERSION: 1.0.4 # Increment as needed. Need to update version for pipeline to create release.

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout and tag creation

jobs:
  SetFilename:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.set_filename.outputs.filename }}
    steps:
      - name: Set filename
        id: set_filename
        run: |
          FILENAME=${{ secrets.DIST_ZIP_NAME }}-${{ env.VERSION }}-${{ env.ENV }}.zip
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          echo "Package filename: $FILENAME"

  RunUnitTests:
    runs-on: ubuntu-latest
    uses: ./.github/templates/test/unit_test.yml@${{github.ref}}

  Build:
    runs-on: ubuntu-latest
    needs: [SetFilename, RunUnitTests]
    uses: ./.github/templates/build/build.yml@$${{github.ref}}
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
      filename: ${{ needs.SetFilename.outputs.filename }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [SetFilename, RunUnitTests, Build]
    uses: ./.github/templates/deploy/deploy.yml@$${{github.ref}}
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
      filename: ${{ needs.SetFilename.outputs.filename }}
