name: Dev Pipeline

on:
  push:
    branches-ignore:
      - main

env:
  ENV: 'dev' # Environment should be static for each env's .yml file.
  VERSION: 1.0.4 # Increment as needed. Need to update version for pipeline to create release.

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout and tag creation

jobs:
  RunDevPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Test
        uses: .github/templates/unit_test.yml

      - name: Set distributable filename
        id: set_filename
        run: |
          FILENAME=${{ secrets.DIST_ZIP_NAME }}-${{ env.VERSION }}-${{ env.ENV }}.zip
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          echo "Package filename: $FILENAME"

      - name: Build
        uses: .github/templates/build.yml
        with:
          env: ${{ inputs.env }}
          version: ${{ inputs.version }}
          filename: ${{ steps.set_filename.outputs.filename }}

      - name: Deploy
        uses: .github/templates/deploy.yml
        with:
          env: ${{ inputs.env }}
          version: ${{ inputs.version }}
          filename: ${{ steps.set_filename.outputs.filename }}
