name: Dev Pipeline

on:
  push:
    branches-ignore:
      - main

env:
  ENV: 'dev'
  VERSION: 1.0.4

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout and tag creation

jobs:
  RunDevPipeline:
    runs-on: ubuntu-latest
    env:
      FILENAME: ${{ secrets.DIST_ZIP_NAME }}-${{ env.VERSION }}-${{ env.ENV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        uses: ./.github/templates/unit_test.yml

      - name: Build
        uses: ./.github/templates/build.yml
        with:
          env: ${{ inputs.env }}
          version: ${{ inputs.version }}
          filename: ${{ variables.FILENAME }}

      - name: Deploy
        uses: ./.github/templates/deploy.yml
        with:
          env: ${{ inputs.env }}
          version: ${{ inputs.version }}
          filename: ${{ variables.FILENAME }}
