name: Release Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Trigger only when tag with version (e.g. 1.0.0) is pushed.

env:
  ENV: 'prod' # Environment should be static for each env's .yml file.
  APP_NAME: 'meltyframedatabot'
  LAMBDA_NAME: 'fgc-aacc-meltyframedatabot'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout and tag creation

jobs:
  SetupParameters:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set_params.outputs.env }}
      version: ${{ steps.set_params.outputs.version }}
      filename: ${{ steps.set_params.outputs.filename }}
      lambda_name: ${{ steps.set_params.outputs.lambda_name }}
    steps:
      # Setup parameters in job because you cannot directly pass variables into input.
      - name: Set parameters
        id: set_params
        # Obtain version from tag name for prod releases.
        run: |
          ENV=${{ env.ENV }}
          VERSION=${{ github.ref#refs/tags/ }}
          FILENAME=${{ env.APP_NAME }}-$VERSION-$ENV
          LAMBDA_NAME=${{ env.LAMBDA_NAME }}
          echo "env=$ENV" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          echo "lambda_name=$LAMBDA_NAME" >> $GITHUB_OUTPUT

  RunUnitTests:
    uses: ./.github/workflows/action_unit_test.yml

  Build:
    needs: [SetupParameters, RunUnitTests]
    uses: ./.github/workflows/action_build.yml
    with:
      env: ${{needs.SetupParameters.outputs.env}}
      filename: ${{needs.SetupParameters.outputs.filename}}
    secrets: inherit

  Deploy:
    needs: [SetupParameters, RunUnitTests, Build]
    uses: ./.github/workflows/action_deploy.yml
    with:
      env: ${{needs.SetupParameters.outputs.env}}
      version: ${{needs.SetupParameters.outputs.version}}
      filename: ${{ needs.SetupParameters.outputs.filename}}
      lambda_name: ${{ needs.SetupParameters.outputs.lambda_name}}
    secrets: inherit
