name: Main CI-CD Pipeline

# Inputs:
#   env - Environment code should deploy to
#   version - Current app version

on:
  workflow_dispatch:

pipeline_variables:
  FILENAME: ${{ secrets.DIST_ZIP_NAME }}-${{ inputs.version }}-${{ inputs.env }}

jobs:
  UnitTest:
    uses: ./.github/templates/unit_test.yml

  Build:
    uses: ./.github/templates/build.yml
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
      filename: ${{ pipeline_variables.FILENAME }}

  Deploy:
    uses: ./.github/templates/deploy.yml
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
      filename: ${{ pipeline_variables.FILENAME }}
